# Generated by Django 6.1 on 2026-09-14 10:01
"""Drop the per-build run table and the two source-version columns.

A result used to be identified by ``(business_date, source_daily_price_version,
source_industry_version)``, so rebuilding a day after public data changed added a
competing row instead of replacing the day's. Results are now keyed by
``business_date`` alone: a rebuild overwrites, and a page picks the rebuild up on
its next request.

``SectorMomentumRun`` goes with the version pair. It existed to make each build
attempt independently observable; the command log does that now, and the derived
writer no longer needs a second write to mark a run successful.

Irreversible in data terms: the version history and the run rows are not
backfilled anywhere.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector_momentum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sectormomentumrun',
            name='sector_mome_busines_145a3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='sectormomentumrun',
            name='sector_mome_status_2627df_idx',
        ),
        migrations.DeleteModel(
            name='SectorMomentumRun',
        ),
        migrations.RemoveConstraint(
            model_name='sectormomentumresult',
            name='sector_momentum_result_source_version_unique',
        ),
        migrations.AlterField(
            model_name='sectormomentumresult',
            name='business_date',
            field=models.DateField(unique=True, verbose_name='业务日期'),
        ),
        migrations.RemoveField(
            model_name='sectormomentumresult',
            name='source_daily_price_version',
        ),
        migrations.RemoveField(
            model_name='sectormomentumresult',
            name='source_industry_version',
        ),
    ]
