# Generated by Django 6.1 on 2026-09-15 05:40
"""让板块动量只用一张表。

结果级的两个数字是**日级**事实，推不出来，所以挪到排行行上按行重复存一份（一天
最多 20 行）。其余六个数 —— 名次、股票数、平均涨跌幅、行业成交额、成交额占比、
综合评分 —— 都是 ``stocks`` 加全市场成交额的函数：实测两天 40 行，从 ``stocks``
现算这六个数 **0 处不符**，名次也正是"按综合评分降序、同分按行业代码升序"。

顺序：先加**可空**的 ``business_date`` / ``published_at`` 与带默认值的两个日级
列 → 用旧的结果行回填 → 收紧 ``business_date`` / ``published_at`` 为非空 → 换约束
与索引 → 删外键与旧表。

发布时间取旧结果行的 ``created_at``，它是页面工具条上「更新于 HH:MM」原本显示的值。

反向只恢复结构，不恢复数据：六个数可以从 ``stocks`` 重算。
"""

import django.utils.timezone
from django.db import migrations, models


def backfill_day_from_result(apps, schema_editor):
    """把结果行的业务日期、写入时刻与两个日级事实搬到这一天的每一条排行行上。"""
    Ranking = apps.get_model('sector_momentum', 'SectorMomentumRanking')
    Result = apps.get_model('sector_momentum', 'SectorMomentumResult')
    database = schema_editor.connection.alias

    days = {
        result.pk: (
            result.business_date,
            result.created_at,
            result.total_market_turnover,
            result.unmapped_stock_count,
        )
        for result in Result.objects.using(database).all().iterator()
    }
    pending = []
    for ranking in Ranking.objects.using(database).all().iterator():
        day = days.get(ranking.result_id)
        if day is None:
            # 排行行没有结果行是损坏数据（外键本该拦住）；跳过而不是编一天出来。
            continue
        (
            ranking.business_date,
            ranking.published_at,
            ranking.total_market_turnover,
            ranking.unmapped_stock_count,
        ) = day
        pending.append(ranking)
    if pending:
        Ranking.objects.using(database).bulk_update(
            pending,
            [
                'business_date',
                'published_at',
                'total_market_turnover',
                'unmapped_stock_count',
            ],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sector_momentum', '0002_drop_run_table_and_source_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectormomentumranking',
            name='business_date',
            field=models.DateField(null=True, verbose_name='业务日期'),
        ),
        migrations.AddField(
            model_name='sectormomentumranking',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='sectormomentumranking',
            name='total_market_turnover',
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=20, verbose_name='全市场成交额'
            ),
        ),
        migrations.AddField(
            model_name='sectormomentumranking',
            name='unmapped_stock_count',
            field=models.PositiveIntegerField(default=0, verbose_name='未映射股票数'),
        ),
        migrations.RunPython(
            backfill_day_from_result,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='sectormomentumranking',
            name='business_date',
            field=models.DateField(verbose_name='业务日期'),
        ),
        migrations.AlterField(
            model_name='sectormomentumranking',
            name='published_at',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
        migrations.AddIndex(
            model_name='sectormomentumranking',
            index=models.Index(
                fields=['business_date', 'metric'],
                name='sector_momentum_day_metric_idx',
            ),
        ),
        migrations.RemoveConstraint(
            model_name='sectormomentumranking',
            name='sector_momentum_metric_rank_unique',
        ),
        migrations.RemoveConstraint(
            model_name='sectormomentumranking',
            name='sector_momentum_metric_industry_unique',
        ),
        migrations.RemoveField(
            model_name='sectormomentumranking',
            name='result',
        ),
        migrations.RemoveField(
            model_name='sectormomentumranking',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='sectormomentumranking',
            name='stock_count',
        ),
        migrations.RemoveField(
            model_name='sectormomentumranking',
            name='average_change_percent',
        ),
        migrations.RemoveField(
            model_name='sectormomentumranking',
            name='industry_turnover',
        ),
        migrations.RemoveField(
            model_name='sectormomentumranking',
            name='market_turnover_ratio',
        ),
        migrations.RemoveField(
            model_name='sectormomentumranking',
            name='score',
        ),
        migrations.AlterModelOptions(
            name='sectormomentumranking',
            options={
                'ordering': ['metric', 'industry_code'],
                'verbose_name': '板块动量行业排行',
                'verbose_name_plural': '板块动量行业排行',
            },
        ),
        migrations.AddConstraint(
            model_name='sectormomentumranking',
            constraint=models.UniqueConstraint(
                fields=('business_date', 'metric', 'industry_code'),
                name='sector_momentum_date_metric_industry_unique',
            ),
        ),
        migrations.DeleteModel(
            name='SectorMomentumResult',
        ),
    ]
