# Generated by Django 6.1 on 2026-09-09 01:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMoveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True, verbose_name='业务日期')),
                ('source_daily_price_version', models.CharField(db_index=True, max_length=64, verbose_name='公共日行情版本')),
                ('sse_rise_count', models.PositiveIntegerField(default=0, verbose_name='上证上涨组数量')),
                ('sse_fall_count', models.PositiveIntegerField(default=0, verbose_name='上证下跌组数量')),
                ('szse_rise_count', models.PositiveIntegerField(default=0, verbose_name='深证上涨组数量')),
                ('szse_fall_count', models.PositiveIntegerField(default=0, verbose_name='深证下跌组数量')),
                ('distinct_stock_count', models.PositiveIntegerField(default=0, verbose_name='涉及股票去重数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '大涨跌幅与大成交量结果',
                'verbose_name_plural': '大涨跌幅与大成交量结果',
                'ordering': ['-business_date', '-created_at'],
                'indexes': [models.Index(fields=['business_date', 'created_at'], name='stock_moves_busines_7dd655_idx')],
                'constraints': [models.UniqueConstraint(fields=('business_date', 'source_daily_price_version'), name='stock_moves_result_source_versions_unique')],
            },
        ),
        migrations.CreateModel(
            name='StockMoveRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_batch_id', models.CharField(max_length=64, unique=True, verbose_name='运行批次标识')),
                ('business_date', models.DateField(db_index=True, verbose_name='业务日期')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], max_length=8, verbose_name='运行状态')),
                ('source_daily_price_version', models.CharField(blank=True, max_length=64, verbose_name='公共日行情版本')),
                ('published_result_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='已发布结果标识')),
                ('total_candidate_count', models.PositiveIntegerField(default=0, verbose_name='涉及股票去重数量')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('error_summary', models.TextField(blank=True, verbose_name='错误摘要')),
            ],
            options={
                'verbose_name': '大涨跌幅与大成交量运行记录',
                'verbose_name_plural': '大涨跌幅与大成交量运行记录',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['business_date', 'started_at'], name='stock_moves_busines_13c55e_idx'), models.Index(fields=['status', 'started_at'], name='stock_moves_status_e49fef_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMoveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('sse_rise', '上证上涨'), ('sse_fall', '上证下跌'), ('szse_rise', '深证上涨'), ('szse_fall', '深证下跌')], max_length=9, verbose_name='分组')),
                ('rank', models.PositiveIntegerField(verbose_name='组内排序')),
                ('stock_code', models.CharField(max_length=6, verbose_name='股票代码')),
                ('stock_name', models.CharField(max_length=64, verbose_name='股票名称')),
                ('parent_industries', models.JSONField(default=list, verbose_name='开盘啦板块快照')),
                ('change_percent', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='涨跌幅（%）')),
                ('turnover', models.DecimalField(decimal_places=4, max_digits=24, verbose_name='成交额（元）')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock_moves.stockmoveresult', verbose_name='分析结果')),
            ],
            options={
                'verbose_name': '大涨跌幅与大成交量股票明细',
                'verbose_name_plural': '大涨跌幅与大成交量股票明细',
                'ordering': ['group', 'rank'],
                'indexes': [models.Index(fields=['result', 'group', 'rank'], name='stock_moves_result__52b507_idx')],
                'constraints': [models.UniqueConstraint(fields=('result', 'group', 'rank'), name='stock_moves_item_result_group_rank_unique'), models.UniqueConstraint(fields=('result', 'stock_code'), name='stock_moves_item_result_stock_unique')],
            },
        ),
    ]
