# Generated by Django 6.1 on 2026-09-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_moves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmoveresult',
            name='warnings',
            field=models.JSONField(default=list, verbose_name='非致命分析警告'),
        ),
    ]
