# Generated by Django 6.1 on 2026-09-12 06:19

from django.db import migrations, models


def clear_results_without_bse_group(apps, schema_editor):
    """Drop derived results that predate the BSE group.

    Rows written before this change only counted qualifying Beijing Stock
    Exchange stocks instead of storing them, and their ``warnings`` still
    contains the "已排除 N 只…" note that is no longer produced. Neither can be
    repaired in place — the items simply are not there — and this table is pure
    derived data that the read path rebuilds from public daily prices on demand
    (see spec §5.8(a)), so clearing it is the cheap and self-healing fix.
    ``StockMoveRun`` history is deliberately left untouched.
    """
    apps.get_model('stock_moves', 'StockMoveResult').objects.using(schema_editor.connection.alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stock_moves', '0002_stockmoveresult_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmoveresult',
            name='bse_count',
            field=models.PositiveIntegerField(default=0, verbose_name='北京证券交易所组数量'),
        ),
        migrations.AlterField(
            model_name='stockmoveitem',
            name='group',
            field=models.CharField(choices=[('sse_rise', '上证上涨'), ('sse_fall', '上证下跌'), ('szse_rise', '深证上涨'), ('szse_fall', '深证下跌'), ('bse', '北京证券交易所')], max_length=9, verbose_name='分组'),
        ),
        migrations.RunPython(
            clear_results_without_bse_group,
            migrations.RunPython.noop,
        ),
    ]

