# Generated by Django 6.1 on 2026-09-12 06:40

from django.db import migrations, models


def clear_results_with_the_merged_bse_group(apps, schema_editor):
    """Drop derived results written while Beijing stocks shared one mixed group.

    Those rows store ``group='bse'``, a value the new choices no longer accept,
    and their ``bse_count`` cannot be split back into rise/fall without
    re-deriving from public daily prices. This table is pure derived data that
    the read path rebuilds on demand (see spec §5.8(a)), so clearing it is the
    cheap and self-healing fix. ``StockMoveRun`` history stays untouched.
    """
    apps.get_model('stock_moves', 'StockMoveResult').objects.using(
        schema_editor.connection.alias
    ).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stock_moves', '0003_stockmove_bse_group'),
    ]

    operations = [
        migrations.RunPython(
            clear_results_with_the_merged_bse_group,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='stockmoveresult',
            name='bse_count',
        ),
        migrations.AddField(
            model_name='stockmoveresult',
            name='bse_rise_count',
            field=models.PositiveIntegerField(default=0, verbose_name='北交所上涨组数量'),
        ),
        migrations.AddField(
            model_name='stockmoveresult',
            name='bse_fall_count',
            field=models.PositiveIntegerField(default=0, verbose_name='北交所下跌组数量'),
        ),
        migrations.AlterField(
            model_name='stockmoveitem',
            name='group',
            field=models.CharField(
                choices=[
                    ('sse_rise', '上证上涨'),
                    ('sse_fall', '上证下跌'),
                    ('szse_rise', '深证上涨'),
                    ('szse_fall', '深证下跌'),
                    ('bse_rise', '北交所上涨'),
                    ('bse_fall', '北交所下跌'),
                ],
                max_length=9,
                verbose_name='分组',
            ),
        ),
    ]
