# Generated by Django 6.1 on 2026-09-12

from django.db import migrations, models


def clear_results_without_an_industry_version(apps, schema_editor):
    """Drop derived results that predate industry-version tracking.

    Rows written before this change carry an empty ``source_industry_version``,
    so the read path can never tell whether their stored ``industries`` still
    matches the current industry mapping — it would happily serve them under a
    version string that claims otherwise, which is exactly the defect this field
    exists to fix. This table is pure derived data that the read path rebuilds
    from local public data on demand (spec §5.8(a)), so clearing it is the cheap,
    self-healing fix. ``StockMoveRun`` history is deliberately left untouched.
    """
    apps.get_model('stock_moves', 'StockMoveResult').objects.using(
        schema_editor.connection.alias
    ).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stock_moves', '0005_rename_parent_industries_to_industries'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockmoveresult',
            name='stock_moves_result_source_versions_unique',
        ),
        migrations.AddField(
            model_name='stockmoveresult',
            name='source_industry_version',
            field=models.CharField(
                db_index=True, max_length=64, verbose_name='行业映射版本'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmoverun',
            name='source_industry_version',
            field=models.CharField(
                blank=True, max_length=64, verbose_name='行业映射版本'
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='stockmoveresult',
            constraint=models.UniqueConstraint(
                fields=(
                    'business_date',
                    'source_daily_price_version',
                    'source_industry_version',
                ),
                name='stock_moves_result_source_versions_unique',
            ),
        ),
        migrations.RunPython(
            clear_results_without_an_industry_version,
            migrations.RunPython.noop,
        ),
    ]
