# Generated by Django 6.1 on 2026-09-14 10:01
"""Drop the per-build run table and the two source-version columns.

A result used to be identified by ``(business_date, source_daily_price_version,
source_industry_version)``, so rebuilding a day after public data changed added a
competing row instead of replacing the day's. Results are now keyed by
``business_date`` alone: a rebuild overwrites, and a page picks the rebuild up on
its next request.

``StockMoveRun`` goes with the version pair. It existed to make each build
attempt independently observable; the command log does that now, and the derived
writer no longer needs a second write to mark a run successful.

Irreversible in data terms: the version history and the run rows are not
backfilled anywhere.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_moves', '0006_stockmoveresult_source_industry_version'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockmoverun',
            name='stock_moves_busines_13c55e_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmoverun',
            name='stock_moves_status_e49fef_idx',
        ),
        migrations.DeleteModel(
            name='StockMoveRun',
        ),
        migrations.RemoveConstraint(
            model_name='stockmoveresult',
            name='stock_moves_result_source_versions_unique',
        ),
        migrations.AlterField(
            model_name='stockmoveresult',
            name='business_date',
            field=models.DateField(unique=True, verbose_name='业务日期'),
        ),
        migrations.RemoveField(
            model_name='stockmoveresult',
            name='source_daily_price_version',
        ),
        migrations.RemoveField(
            model_name='stockmoveresult',
            name='source_industry_version',
        ),
    ]
