# Generated by Django 6.1 on 2026-09-15 05:40
"""让大涨跌幅与大成交量个股只用一张表。

结果级的数字都是这一天明细行的函数：实测两个业务日期，六组计数与涉及股票去重数由
行推出 **0 处不符**；非致命告警也能由 ``stock_name`` / ``industries`` 是否为空精确
重建（``analysis.py`` 里那两条文案就是按这两个条件产生的）。所以
``StockMoveResult`` 整张表删掉，``business_date`` 与发布时间挪到明细行上。

顺序：先加**可空**的两列 → 用旧的结果行回填 → 收紧为非空 → 换约束与索引 → 删外键
与旧表。这样已有结果不需要重建就能继续被读出来。

发布时间取旧结果行的 ``created_at``：它是"这份数据写进数据库的时刻"，也是页面工具
条上「更新于 HH:MM」原本显示的值。

反向只恢复结构，不恢复数据：结果行的六组计数与去重数可以从明细行重算，不需要回填。
"""

from django.db import migrations, models


def backfill_day_from_result(apps, schema_editor):
    """把结果行的业务日期与写入时刻搬到这一天的每一条明细行上。"""
    StockMoveItem = apps.get_model('stock_moves', 'StockMoveItem')
    StockMoveResult = apps.get_model('stock_moves', 'StockMoveResult')
    database = schema_editor.connection.alias

    days = {
        result.pk: (result.business_date, result.created_at)
        for result in StockMoveResult.objects.using(database).all().iterator()
    }
    pending = []
    for item in StockMoveItem.objects.using(database).all().iterator():
        day = days.get(item.result_id)
        if day is None:
            # 明细行没有结果行是损坏数据（外键本该拦住）；跳过而不是编一个日期出来。
            continue
        item.business_date, item.published_at = day
        pending.append(item)
    if pending:
        StockMoveItem.objects.using(database).bulk_update(
            pending, ['business_date', 'published_at']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('stock_moves', '0007_drop_run_table_and_source_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmoveitem',
            name='business_date',
            field=models.DateField(null=True, verbose_name='业务日期'),
        ),
        migrations.AddField(
            model_name='stockmoveitem',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='发布时间'),
        ),
        migrations.RunPython(
            backfill_day_from_result,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='stockmoveitem',
            name='business_date',
            field=models.DateField(verbose_name='业务日期'),
        ),
        migrations.AlterField(
            model_name='stockmoveitem',
            name='published_at',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
        migrations.RemoveIndex(
            model_name='stockmoveitem',
            name='stock_moves_result__52b507_idx',
        ),
        migrations.AddIndex(
            model_name='stockmoveitem',
            index=models.Index(
                fields=['business_date', 'group', 'rank'],
                name='stock_moves_day_group_rank_idx',
            ),
        ),
        migrations.RemoveConstraint(
            model_name='stockmoveitem',
            name='stock_moves_item_result_group_rank_unique',
        ),
        migrations.RemoveConstraint(
            model_name='stockmoveitem',
            name='stock_moves_item_result_stock_unique',
        ),
        migrations.RemoveField(
            model_name='stockmoveitem',
            name='result',
        ),
        migrations.AddConstraint(
            model_name='stockmoveitem',
            constraint=models.UniqueConstraint(
                fields=('business_date', 'group', 'rank'),
                name='stock_moves_item_date_group_rank_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='stockmoveitem',
            constraint=models.UniqueConstraint(
                fields=('business_date', 'stock_code'),
                name='stock_moves_item_date_stock_unique',
            ),
        ),
        migrations.DeleteModel(
            name='StockMoveResult',
        ),
    ]
