"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

from core.module_registry import get_enabled_app_configs

from backend.env import (
    get_bool_setting,
    get_list_setting,
    get_path_setting,
    get_setting,
    get_required_setting,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_required_setting('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_setting('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = get_list_setting('DJANGO_ALLOWED_HOSTS')
DATA_COMMAND_LOG_LEVEL = (get_setting('DATA_COMMAND_LOG_LEVEL', 'INFO') or 'INFO').upper()


# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    *get_enabled_app_configs(),
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': get_path_setting('CORE_DATABASE_PATH'),
    },
    'kaipanla': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': get_path_setting('KAIPANLA_DATABASE_PATH'),
    },
    'eastmoney': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': get_path_setting('EASTMONEY_DATABASE_PATH'),
    },
    'stock_moves': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': get_path_setting('STOCK_MOVES_DATABASE_PATH'),
    },
    'sector_momentum': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': get_path_setting('SECTOR_MOMENTUM_DATABASE_PATH'),
    },
    'hundred_day': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': get_path_setting('HUNDRED_DAY_DATABASE_PATH'),
    },
}
DATABASE_ROUTERS = ['backend.db_router.AppDatabaseRouter']


SESSION_COOKIE_SECURE = get_bool_setting('SESSION_COOKIE_SECURE', default=True)
SESSION_COOKIE_HTTPONLY = get_bool_setting('SESSION_COOKIE_HTTPONLY', default=True)
SESSION_COOKIE_SAMESITE = get_setting('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SECURE = get_bool_setting('CSRF_COOKIE_SECURE', default=True)
CSRF_COOKIE_SAMESITE = get_setting('CSRF_COOKIE_SAMESITE', 'Lax')
CSRF_TRUSTED_ORIGINS = get_list_setting('CSRF_TRUSTED_ORIGINS')
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'core.management': {
            'handlers': ['console'],
            'level': DATA_COMMAND_LOG_LEVEL,
            'propagate': False,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = get_required_setting('DJANGO_TIME_ZONE')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
