# Generated by Django 6.1 on 2026-09-09 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HundredDayResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True, verbose_name='业务日期')),
                ('source_daily_price_version', models.CharField(max_length=64, verbose_name='公共日行情版本')),
                ('source_industry_version', models.CharField(max_length=64, verbose_name='行业映射版本')),
                ('valid_stock_count', models.PositiveIntegerField(default=0, verbose_name='有效股票数')),
                ('new_high_count', models.PositiveIntegerField(default=0, verbose_name='新高数量')),
                ('new_low_count', models.PositiveIntegerField(default=0, verbose_name='新低数量')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '百日新高新低结果',
                'verbose_name_plural': '百日新高新低结果',
                'ordering': ['-business_date', '-created_at'],
                'indexes': [models.Index(fields=['business_date', 'created_at'], name='hundred_day_busines_26632b_idx')],
                'constraints': [models.UniqueConstraint(fields=('business_date', 'source_daily_price_version', 'source_industry_version'), name='hundred_day_result_source_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='HundredDayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_batch_id', models.CharField(max_length=64, unique=True, verbose_name='运行批次标识')),
                ('business_date', models.DateField(db_index=True, verbose_name='业务日期')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], max_length=8, verbose_name='运行状态')),
                ('source_daily_price_version', models.CharField(blank=True, max_length=64, verbose_name='公共日行情版本')),
                ('source_industry_version', models.CharField(blank=True, max_length=64, verbose_name='行业映射版本')),
                ('published_result_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='已发布结果标识')),
                ('valid_stock_count', models.PositiveIntegerField(default=0, verbose_name='有效股票数')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('error_summary', models.TextField(blank=True, verbose_name='错误摘要')),
            ],
            options={
                'verbose_name': '百日新高新低运行记录',
                'verbose_name_plural': '百日新高新低运行记录',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['business_date', 'started_at'], name='hundred_day_busines_215be3_idx'), models.Index(fields=['status', 'started_at'], name='hundred_day_status_c808af_idx')],
            },
        ),
        migrations.CreateModel(
            name='HundredDayIndustrySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_code', models.CharField(max_length=32, verbose_name='行业代码')),
                ('industry_name', models.CharField(max_length=64, verbose_name='行业名称')),
                ('stock_count', models.PositiveIntegerField(default=0, verbose_name='行业股票数')),
                ('new_high_count', models.PositiveIntegerField(default=0, verbose_name='新高数量')),
                ('new_low_count', models.PositiveIntegerField(default=0, verbose_name='新低数量')),
                ('new_high_stocks', models.JSONField(default=list, verbose_name='新高股票明细')),
                ('new_low_stocks', models.JSONField(default=list, verbose_name='新低股票明细')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_summaries', to='hundred_day.hundreddayresult', verbose_name='分析结果')),
            ],
            options={
                'verbose_name': '百日新高新低父行业汇总',
                'verbose_name_plural': '百日新高新低父行业汇总',
                'ordering': ['industry_code'],
                'constraints': [models.UniqueConstraint(fields=('result', 'industry_code'), name='hundred_day_result_industry_unique')],
            },
        ),
        migrations.CreateModel(
            name='HundredDayStockFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=6, verbose_name='股票代码')),
                ('stock_name', models.CharField(max_length=64, verbose_name='股票名称')),
                ('parent_industries', models.JSONField(default=list, verbose_name='父行业快照')),
                ('is_new_high', models.BooleanField(default=False, verbose_name='是否新高')),
                ('is_new_low', models.BooleanField(default=False, verbose_name='是否新低')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_flags', to='hundred_day.hundreddayresult', verbose_name='分析结果')),
            ],
            options={
                'verbose_name': '百日新高新低股票标志',
                'verbose_name_plural': '百日新高新低股票标志',
                'ordering': ['stock_code'],
                'constraints': [models.UniqueConstraint(fields=('result', 'stock_code'), name='hundred_day_result_stock_unique')],
            },
        ),
        migrations.CreateModel(
            name='HundredDayTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('valid_stock_count', models.PositiveIntegerField(default=0, verbose_name='有效股票数')),
                ('new_high_count', models.PositiveIntegerField(default=0, verbose_name='新高数量')),
                ('new_low_count', models.PositiveIntegerField(default=0, verbose_name='新低数量')),
                ('new_high_ratio', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='新高占比')),
                ('new_low_ratio', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='新低占比')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_points', to='hundred_day.hundreddayresult', verbose_name='分析结果')),
            ],
            options={
                'verbose_name': '百日新高新低趋势点',
                'verbose_name_plural': '百日新高新低趋势点',
                'ordering': ['trade_date'],
                'constraints': [models.UniqueConstraint(fields=('result', 'trade_date'), name='hundred_day_result_trend_date_unique')],
            },
        ),
    ]
