# Generated by Django 6.1 on 2026-09-15 03:45
"""让被标记的股票只存一份。

``HundredDayIndustrySummary`` 的 ``new_high_stocks`` / ``new_low_stocks`` 是
把 ``HundredDayStockFlag`` 里同一批股票按行业又展开了一遍。实测：9/11 那份
21 新高 / 310 新低、9/14 那份 44 新高 / 143 新低，两个集合与个股标志完全一致；
一只股票属于多个行业时，它在每个行业的名单里都会重复出现一次。名单可以按
``StockFlag.industries`` 分组精确重建，所以这里把它删掉。

行业明细里每只股票还要展示当日涨幅与成交额，而这两个值原本只存在 JSON 里。
它们不能读时去 ``core`` 现查 —— 结果是按天发布的快照，读路径不该依赖事后可能
变化的公共行情。因此先把两列加在 ``HundredDayStockFlag`` 上，再把 JSON 里的值
搬过去，最后才删列：这样已有结果不需要重建就能继续被读出来。

行业汇总保留 ``stock_count`` / ``new_high_count`` / ``new_low_count``：成分股
总数推不出来（0 新高 0 新低的行业也要有一行），它属于行业级事实。

反向只恢复列，不恢复数据：搬走的行情不回填回 JSON。
"""

from django.db import migrations, models


def backfill_quotes_from_industry_details(apps, schema_editor):
    """把行业明细 JSON 里的当日行情搬进个股标志。

    按 ``(result_id, stock_code)`` 取值而不是只按股票代码：不同结果对应不同交易日，
    同一只股票在不同交易日的涨幅与成交额并不相同。
    """
    StockFlag = apps.get_model('hundred_day', 'HundredDayStockFlag')
    IndustrySummary = apps.get_model('hundred_day', 'HundredDayIndustrySummary')
    database = schema_editor.connection.alias

    quotes: dict[tuple[int, str], tuple] = {}
    for summary in IndustrySummary.objects.using(database).all().iterator():
        for entries in (summary.new_high_stocks, summary.new_low_stocks):
            for entry in entries or ():
                stock_code = entry.get('code')
                if stock_code is None:
                    continue
                quotes.setdefault(
                    (summary.result_id, stock_code),
                    (entry.get('change_percent'), entry.get('turnover')),
                )

    pending = []
    for flag in StockFlag.objects.using(database).all().iterator():
        quote = quotes.get((flag.result_id, flag.stock_code))
        if quote is None:
            # 行业映射没覆盖到的被标记股票：原本也不会出现在任何行业名单里。
            continue
        flag.change_percent, flag.turnover = quote
        pending.append(flag)
    if pending:
        StockFlag.objects.using(database).bulk_update(
            pending, ['change_percent', 'turnover']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('hundred_day', '0004_drop_run_table_and_source_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='hundreddaystockflag',
            name='change_percent',
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=12,
                null=True,
                verbose_name='涨跌幅（%）',
            ),
        ),
        migrations.AddField(
            model_name='hundreddaystockflag',
            name='turnover',
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=24,
                null=True,
                verbose_name='成交额（元）',
            ),
        ),
        migrations.RunPython(
            backfill_quotes_from_industry_details,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='hundreddayindustrysummary',
            name='new_high_stocks',
        ),
        migrations.RemoveField(
            model_name='hundreddayindustrysummary',
            name='new_low_stocks',
        ),
    ]
