# Generated by Django 6.1 on 2026-09-15 05:40
"""把百日新高新低从四张表收到三张表。

``HundredDayResult`` 与 ``HundredDayTrend`` 本来就是同一个粒度（一个交易日的市场
宽度），而且业务日期那一行与"当日结果"逐字段相等 —— 实测两天：9/11 是
(5550, 21, 310)、9/14 是 (5550, 44, 143)，趋势点只是多了两个比值。所以两者合并
成 ``HundredDayBreadth``：``business_date`` 是这次发布的键，``trade_date`` 是这一
行数据自己的交易日。页面的"当日"就是 ``trade_date`` 等于 ``business_date`` 的那一
行，"趋势"是同一个 ``business_date`` 下的全部行。两个比值由除法现算，不再落库。

行业汇总只留 ``stock_count``：它含**未被标记**的成分股（实测 104/104 个行业都与
"该行业被标记股票数"不同，例如养殖业 36 只成分股、0 只被标记），推不出来；而行业
级的新高/新低数量是 ``HundredDayStockFlag`` 的函数，读路径按 ``industries`` 分组
现算。

三张子表的外键换成 ``business_date``：单表/少表之后没有"结果行"可以指向，
``business_date`` 本身就是发布的键。

顺序：先重命名趋势表 → 三张表各加**可空**的 ``business_date`` 与发布时间 → 回填 →
收紧为非空 → 删列、换约束与索引 → 删旧表。

回填前先校验"业务日期那一行 == 旧结果行"：不一致就说明数据已经对不上，宁可让迁移
失败并要求重跑 ``build_hundred_day``，也不静默丢掉结果行的数字。

反向只恢复结构，不恢复数据。
"""

import django.utils.timezone
from django.db import migrations, models


def backfill_business_date(apps, schema_editor):
    """把旧结果行的业务日期与写入时刻搬到三张表上，并校验当日那一行相等。"""
    Result = apps.get_model('hundred_day', 'HundredDayResult')
    Breadth = apps.get_model('hundred_day', 'HundredDayBreadth')
    Flag = apps.get_model('hundred_day', 'HundredDayStockFlag')
    Summary = apps.get_model('hundred_day', 'HundredDayIndustrySummary')
    database = schema_editor.connection.alias

    days = {
        result.pk: {
            'business_date': result.business_date,
            'published_at': result.created_at,
            'valid_stock_count': result.valid_stock_count,
            'new_high_count': result.new_high_count,
            'new_low_count': result.new_low_count,
        }
        for result in Result.objects.using(database).all().iterator()
    }

    for result_id, day in days.items():
        point = (
            Breadth.objects.using(database)
            .filter(result_id=result_id, trade_date=day['business_date'])
            .first()
        )
        counts = None if point is None else (
            point.valid_stock_count, point.new_high_count, point.new_low_count
        )
        expected = (
            day['valid_stock_count'], day['new_high_count'], day['new_low_count']
        )
        if counts != expected:
            raise RuntimeError(
                'Hundred-day data is inconsistent: the trend point for '
                f'{day["business_date"]} is {counts} but the stored result is '
                f'{expected}. Re-run build_hundred_day for that date, then retry '
                'this migration.'
            )

    breadth = []
    for point in Breadth.objects.using(database).all().iterator():
        day = days.get(point.result_id)
        if day is None:
            # 没有结果行是损坏数据（外键本该拦住）；跳过而不是编一天出来。
            continue
        point.business_date = day['business_date']
        point.published_at = day['published_at']
        breadth.append(point)
    if breadth:
        Breadth.objects.using(database).bulk_update(
            breadth, ['business_date', 'published_at']
        )

    flags = []
    for flag in Flag.objects.using(database).all().iterator():
        day = days.get(flag.result_id)
        if day is None:
            continue
        flag.business_date = day['business_date']
        flags.append(flag)
    if flags:
        Flag.objects.using(database).bulk_update(flags, ['business_date'])

    summaries = []
    for summary in Summary.objects.using(database).all().iterator():
        day = days.get(summary.result_id)
        if day is None:
            continue
        summary.business_date = day['business_date']
        summaries.append(summary)
    if summaries:
        Summary.objects.using(database).bulk_update(summaries, ['business_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('hundred_day', '0005_drop_industry_stock_detail_json'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HundredDayTrend',
            new_name='HundredDayBreadth',
        ),
        migrations.AddField(
            model_name='hundreddaybreadth',
            name='business_date',
            field=models.DateField(null=True, verbose_name='业务日期'),
        ),
        migrations.AddField(
            model_name='hundreddaybreadth',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='hundreddaystockflag',
            name='business_date',
            field=models.DateField(null=True, verbose_name='业务日期'),
        ),
        migrations.AddField(
            model_name='hundreddayindustrysummary',
            name='business_date',
            field=models.DateField(null=True, verbose_name='业务日期'),
        ),
        migrations.RunPython(
            backfill_business_date,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='hundreddaybreadth',
            name='business_date',
            field=models.DateField(verbose_name='业务日期'),
        ),
        migrations.AlterField(
            model_name='hundreddaybreadth',
            name='published_at',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='hundreddaystockflag',
            name='business_date',
            field=models.DateField(verbose_name='业务日期'),
        ),
        migrations.AlterField(
            model_name='hundreddayindustrysummary',
            name='business_date',
            field=models.DateField(verbose_name='业务日期'),
        ),
        migrations.AlterModelOptions(
            name='hundreddaybreadth',
            options={
                'ordering': ['trade_date'],
                'verbose_name': '百日市场宽度',
                'verbose_name_plural': '百日市场宽度',
            },
        ),
        migrations.RemoveConstraint(
            model_name='hundreddaybreadth',
            name='hundred_day_result_trend_date_unique',
        ),
        migrations.RemoveField(
            model_name='hundreddaybreadth',
            name='new_high_ratio',
        ),
        migrations.RemoveField(
            model_name='hundreddaybreadth',
            name='new_low_ratio',
        ),
        migrations.RemoveField(
            model_name='hundreddaybreadth',
            name='result',
        ),
        migrations.AddIndex(
            model_name='hundreddaybreadth',
            index=models.Index(
                fields=['business_date', 'trade_date'],
                name='hundred_day_day_trade_date_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='hundreddaybreadth',
            constraint=models.UniqueConstraint(
                fields=('business_date', 'trade_date'),
                name='hundred_day_breadth_date_trade_date_unique',
            ),
        ),
        migrations.RemoveConstraint(
            model_name='hundreddaystockflag',
            name='hundred_day_result_stock_unique',
        ),
        migrations.RemoveField(
            model_name='hundreddaystockflag',
            name='result',
        ),
        migrations.AddConstraint(
            model_name='hundreddaystockflag',
            constraint=models.UniqueConstraint(
                fields=('business_date', 'stock_code'),
                name='hundred_day_date_stock_unique',
            ),
        ),
        migrations.RemoveConstraint(
            model_name='hundreddayindustrysummary',
            name='hundred_day_result_industry_unique',
        ),
        migrations.RemoveField(
            model_name='hundreddayindustrysummary',
            name='new_high_count',
        ),
        migrations.RemoveField(
            model_name='hundreddayindustrysummary',
            name='new_low_count',
        ),
        migrations.RemoveField(
            model_name='hundreddayindustrysummary',
            name='result',
        ),
        migrations.AddConstraint(
            model_name='hundreddayindustrysummary',
            constraint=models.UniqueConstraint(
                fields=('business_date', 'industry_code'),
                name='hundred_day_date_industry_unique',
            ),
        ),
        migrations.DeleteModel(
            name='HundredDayResult',
        ),
    ]
