# Generated by Django 6.1 on 2026-09-09 01:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EastmoneySectorFundFlowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_batch_id', models.CharField(max_length=64, unique=True, verbose_name='采集批次标识')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日')),
                ('snapshot_time', models.DateTimeField(db_index=True, verbose_name='快照时间')),
                ('status', models.CharField(choices=[('running', '运行中'), ('complete', '完整'), ('partial', '部分完成'), ('failed', '失败')], max_length=8, verbose_name='运行状态')),
                ('inflow_status', models.CharField(choices=[('pending', '待执行'), ('complete', '成功'), ('failed', '失败')], default='pending', max_length=8, verbose_name='流入榜状态')),
                ('outflow_status', models.CharField(choices=[('pending', '待执行'), ('complete', '成功'), ('failed', '失败')], default='pending', max_length=8, verbose_name='流出榜状态')),
                ('inflow_record_count', models.PositiveIntegerField(default=0, verbose_name='流入榜记录数')),
                ('outflow_record_count', models.PositiveIntegerField(default=0, verbose_name='流出榜记录数')),
                ('inflow_error_summary', models.TextField(blank=True, verbose_name='流入榜错误摘要')),
                ('outflow_error_summary', models.TextField(blank=True, verbose_name='流出榜错误摘要')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('error_summary', models.TextField(blank=True, verbose_name='错误摘要')),
            ],
            options={
                'verbose_name': '东方财富板块资金流采集运行',
                'verbose_name_plural': '东方财富板块资金流采集运行',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['trade_date', 'snapshot_time'], name='eastmoney_e_trade_d_0fa922_idx'), models.Index(fields=['status', 'started_at'], name='eastmoney_e_status_073290_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status', 'running'), models.Q(('status', 'complete'), ('inflow_status', 'complete'), ('outflow_status', 'complete')), models.Q(('status', 'partial'), models.Q(models.Q(('inflow_status', 'complete'), ('outflow_status', 'failed')), models.Q(('inflow_status', 'failed'), ('outflow_status', 'complete')), _connector='OR')), models.Q(('status', 'failed'), ('inflow_status', 'failed'), ('outflow_status', 'failed')), _connector='OR'), name='eastmoney_run_status_matches_direction_statuses')],
            },
        ),
        migrations.CreateModel(
            name='EastmoneySectorFundFlowSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(db_index=True, max_length=16, verbose_name='东方财富板块代码')),
                ('sector_name', models.CharField(max_length=64, verbose_name='东方财富板块名称')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日')),
                ('snapshot_time', models.DateTimeField(db_index=True, verbose_name='快照时间')),
                ('latest_index', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='板块指数')),
                ('change_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='涨跌幅（%）')),
                ('main_net_inflow', models.DecimalField(decimal_places=2, max_digits=24, verbose_name='主力净流入（元）')),
                ('main_net_inflow_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='主力净占比（%）')),
                ('super_large_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='超大单净流入（元）')),
                ('large_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='大单净流入（元）')),
                ('medium_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='中单净流入（元）')),
                ('small_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='小单净流入（元）')),
                ('source_batch_id', models.CharField(db_index=True, max_length=64, verbose_name='采集批次标识')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '东方财富板块资金流快照',
                'verbose_name_plural': '东方财富板块资金流快照',
                'ordering': ['snapshot_time', 'sector_code'],
                'indexes': [models.Index(fields=['sector_code', 'trade_date'], name='eastmoney_e_sector__1b8b1d_idx'), models.Index(fields=['trade_date', 'snapshot_time'], name='eastmoney_e_trade_d_f1de5a_idx')],
                'constraints': [models.UniqueConstraint(fields=('sector_code', 'snapshot_time'), name='eastmoney_snapshot_sector_time_unique')],
            },
        ),
    ]
