# Generated by Django 6.1 on 2026-09-08 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KaipanlaSectorFundFlowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_batch_id', models.CharField(max_length=64, unique=True, verbose_name='采集批次标识')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日')),
                ('snapshot_time', models.DateTimeField(db_index=True, verbose_name='快照时间（5分钟对齐）')),
                ('status', models.CharField(choices=[('running', '运行中'), ('complete', '完整'), ('failed', '失败')], max_length=8, verbose_name='运行状态')),
                ('expected_page_count', models.PositiveIntegerField(default=0, verbose_name='预计页数')),
                ('completed_page_count', models.PositiveIntegerField(default=0, verbose_name='完成页数')),
                ('failed_page_offsets', models.JSONField(default=list, verbose_name='失败页偏移量')),
                ('expected_record_count', models.PositiveIntegerField(default=0, verbose_name='预计记录数')),
                ('actual_record_count', models.PositiveIntegerField(default=0, verbose_name='实际记录数')),
                ('missing_record_count', models.PositiveIntegerField(default=0, verbose_name='缺失记录数')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('error_summary', models.TextField(blank=True, verbose_name='错误摘要')),
            ],
            options={
                'verbose_name': '开盘啦板块资金流采集运行',
                'verbose_name_plural': '开盘啦板块资金流采集运行',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['trade_date', 'snapshot_time'], name='kaipanla_ka_trade_d_905837_idx'), models.Index(fields=['status', 'started_at'], name='kaipanla_ka_status_57d104_idx')],
            },
        ),
        migrations.CreateModel(
            name='KaipanlaSectorFundFlowSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(db_index=True, max_length=16, verbose_name='开盘啦板块代码')),
                ('sector_name', models.CharField(max_length=64, verbose_name='开盘啦板块名称')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日')),
                ('snapshot_time', models.DateTimeField(db_index=True, verbose_name='快照时间（5分钟对齐）')),
                ('change_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='涨跌幅（%）')),
                ('main_net_inflow', models.DecimalField(decimal_places=2, max_digits=24, verbose_name='主力净流入（元）')),
                ('main_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='主力买入（元）')),
                ('main_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='主力卖出（元）')),
                ('large_order_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='大单净额（元）')),
                ('volume_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='量比')),
                ('turnover_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='成交额（元）')),
                ('float_market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='流通市值（元）')),
                ('total_market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='总市值（元）')),
                ('source_batch_id', models.CharField(db_index=True, max_length=64, verbose_name='采集批次标识')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '开盘啦板块资金流快照',
                'verbose_name_plural': '开盘啦板块资金流快照',
                'ordering': ['snapshot_time', 'sector_code'],
                'indexes': [models.Index(fields=['sector_code', 'trade_date'], name='kaipanla_ka_sector__f356f2_idx'), models.Index(fields=['trade_date', 'snapshot_time'], name='kaipanla_ka_trade_d_e64706_idx')],
                'constraints': [models.UniqueConstraint(fields=('sector_code', 'snapshot_time'), name='kaipanla_snapshot_sector_time_unique')],
            },
        ),
    ]
