# Generated by Django 6.1 on 2026-09-14 05:54
"""Drop the collection-run table and the two cross-database source columns.

The module used to register a ``DataVersion`` in the core database and filter its
own rows by the resulting "published version" strings, with a run table recording
how each paginated fetch went. Both are gone: a snapshot is published the moment
its own transaction commits, and a collection's outcome lives in the command log.

``0002`` (which added ``source_data_version`` and backfilled it from
``DataVersion``) is deliberately left untouched — it is applied history on every
existing database, and rewriting it would make ``showmigrations`` disagree with
what actually ran. Its column is dropped here instead. (The one change made to
it is a guard so its backfill survives on a database where ``core/0006`` has
already removed the model it reads; see the note there.)

This migration is irreversible in data terms: the dropped columns and the whole
run table are not backfilled anywhere. The values they held are log fields now.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaipanla', '0002_kaipanlasectorfundflowsnapshot_source_data_version'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kaipanlasectorfundflowrun',
            name='kaipanla_ka_trade_d_905837_idx',
        ),
        migrations.RemoveIndex(
            model_name='kaipanlasectorfundflowrun',
            name='kaipanla_ka_status_57d104_idx',
        ),
        migrations.DeleteModel(
            name='KaipanlaSectorFundFlowRun',
        ),
        migrations.RemoveField(
            model_name='kaipanlasectorfundflowsnapshot',
            name='source_batch_id',
        ),
        migrations.RemoveField(
            model_name='kaipanlasectorfundflowsnapshot',
            name='source_data_version',
        ),
    ]
