# Generated by Django 6.1 on 2026-09-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_code', models.CharField(max_length=32, unique=True)),
                ('industry_name', models.CharField(max_length=64)),
                ('industry_level', models.CharField(choices=[('parent', '父行业'), ('child', '子行业')], max_length=6)),
                ('stock_codes', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['industry_level', 'industry_code'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thscode', models.CharField(max_length=32, unique=True)),
                ('stock_code', models.CharField(max_length=6, unique=True)),
                ('stock_name', models.CharField(max_length=64)),
                ('exchange', models.CharField(choices=[('sse', '上海证券交易所'), ('szse', '深圳证券交易所'), ('bse', '北京证券交易所')], max_length=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['stock_code'],
            },
        ),
        migrations.CreateModel(
            name='TradingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['trade_date'],
            },
        ),
    ]
