# Generated by Django 6.1 on 2026-09-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datasets'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulerunstatus',
            name='completeness',
            field=models.CharField(choices=[('running', '运行中'), ('complete', '完整'), ('partial', '部分完成'), ('failed', '失败')], default='running', max_length=8),
        ),
    ]
