# Generated by Django 6.1 on 2026-09-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_run_status_completeness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrysnapshot',
            options={'ordering': ['industry_code']},
        ),
        migrations.RemoveField(
            model_name='industrysnapshot',
            name='industry_level',
        ),
    ]
