# Generated by Django 6.1 on 2026-09-14 10:01
"""Drop the dataset-version and run-status tables.

``DataVersion`` recorded "this dataset has a complete row for this business day"
and ``ModuleRunStatus`` recorded "the last run of this dataset succeeded". Both
sat *beside* the data and had to be kept in step with it by hand, which is what
made a partially written day representable at all.

They are gone. The sync commands now validate coverage first and write the whole
day inside one transaction, so the rows themselves are the record: a day either
carries its full set of rows or carries none. What used to be a status row is a
line in the command log.

``DailyPrice.source_data_version`` goes with them — with no version to compare
against, the column had no reader. ``DailyPrice.source_batch_id`` stays: it is
"which sync run wrote this row", a traceability field the admin shows, not a
version.

Irreversible in data terms: the dropped rows are not backfilled anywhere.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_tradingday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataVersion',
        ),
        migrations.RemoveConstraint(
            model_name='modulerunstatus',
            name='core_module_run_status_module_dataset_unique',
        ),
        migrations.DeleteModel(
            name='ModuleRunStatus',
        ),
        migrations.RemoveField(
            model_name='dailyprice',
            name='source_data_version',
        ),
    ]
